/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SchemaDotjsonRouteImport } from "./routes/schema[.]json";
import { Route as DashboardRouteRouteImport } from "./routes/dashboard/route";
import { Route as AuthRouteRouteImport } from "./routes/auth/route";
import { Route as HomeRouteRouteImport } from "./routes/_home/route";
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index";
import { Route as AuthIndexRouteImport } from "./routes/auth/index";
import { Route as HomeIndexRouteImport } from "./routes/_home/index";
import { Route as PrinterResumeIdRouteImport } from "./routes/printer/$resumeId";
import { Route as DashboardHistoryRouteImport } from "./routes/dashboard/history";
import { Route as AuthVerify2faBackupRouteImport } from "./routes/auth/verify-2fa-backup";
import { Route as AuthVerify2faRouteImport } from "./routes/auth/verify-2fa";
import { Route as AuthResumePasswordRouteImport } from "./routes/auth/resume-password";
import { Route as AuthResetPasswordRouteImport } from "./routes/auth/reset-password";
import { Route as AuthRegisterRouteImport } from "./routes/auth/register";
import { Route as AuthLoginRouteImport } from "./routes/auth/login";
import { Route as AuthForgotPasswordRouteImport } from "./routes/auth/forgot-password";
import { Route as ApiSimpleAuthRouteImport } from "./routes/api/simple-auth";
import { Route as ApiHealthRouteImport } from "./routes/api/health";
import { Route as UsernameSlugRouteImport } from "./routes/$username/$slug";
import { Route as CoverLetterIdRouteRouteImport } from "./routes/cover-letter/$id/route";
import { Route as BuilderResumeIdRouteRouteImport } from "./routes/builder/$resumeId/route";
import { Route as DashboardResumesIndexRouteImport } from "./routes/dashboard/resumes/index";
import { Route as DashboardCoverLettersIndexRouteImport } from "./routes/dashboard/cover-letters/index";
import { Route as CoverLetterIdIndexRouteImport } from "./routes/cover-letter/$id/index";
import { Route as BuilderResumeIdIndexRouteImport } from "./routes/builder/$resumeId/index";
import { Route as UploadsUserIdSplatRouteImport } from "./routes/uploads/$userId.$";
import { Route as DashboardSettingsProfileRouteImport } from "./routes/dashboard/settings/profile";
import { Route as DashboardSettingsPreferencesRouteImport } from "./routes/dashboard/settings/preferences";
import { Route as DashboardSettingsIntegrationsRouteImport } from "./routes/dashboard/settings/integrations";
import { Route as DashboardSettingsDangerZoneRouteImport } from "./routes/dashboard/settings/danger-zone";
import { Route as DashboardSettingsApiKeysRouteImport } from "./routes/dashboard/settings/api-keys";
import { Route as DashboardSettingsAiRouteImport } from "./routes/dashboard/settings/ai";
import { Route as DashboardCoverLettersListRouteImport } from "./routes/dashboard/cover-letters/list";
import { Route as ApiRpcSplatRouteImport } from "./routes/api/rpc.$";
import { Route as ApiOpenapiSplatRouteImport } from "./routes/api/openapi.$";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth.$";
import { Route as BuilderCoverLetterIdRouteRouteImport } from "./routes/builder/cover-letter/$id/route";
import { Route as DashboardSettingsAuthenticationIndexRouteImport } from "./routes/dashboard/settings/authentication/index";
import { Route as BuilderCoverLetterIdIndexRouteImport } from "./routes/builder/cover-letter/$id/index";

const SchemaDotjsonRoute = SchemaDotjsonRouteImport.update({
  id: "/schema.json",
  path: "/schema.json",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any);
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: "/_home",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthRouteRoute,
} as any);
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => HomeRouteRoute,
} as any);
const PrinterResumeIdRoute = PrinterResumeIdRouteImport.update({
  id: "/printer/$resumeId",
  path: "/printer/$resumeId",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: "/history",
  path: "/history",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const AuthVerify2faBackupRoute = AuthVerify2faBackupRouteImport.update({
  id: "/verify-2fa-backup",
  path: "/verify-2fa-backup",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthVerify2faRoute = AuthVerify2faRouteImport.update({
  id: "/verify-2fa",
  path: "/verify-2fa",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthResumePasswordRoute = AuthResumePasswordRouteImport.update({
  id: "/resume-password",
  path: "/resume-password",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => AuthRouteRoute,
} as any);
const ApiSimpleAuthRoute = ApiSimpleAuthRouteImport.update({
  id: "/api/simple-auth",
  path: "/api/simple-auth",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: "/api/health",
  path: "/api/health",
  getParentRoute: () => rootRouteImport,
} as any);
const UsernameSlugRoute = UsernameSlugRouteImport.update({
  id: "/$username/$slug",
  path: "/$username/$slug",
  getParentRoute: () => rootRouteImport,
} as any);
const CoverLetterIdRouteRoute = CoverLetterIdRouteRouteImport.update({
  id: "/cover-letter/$id",
  path: "/cover-letter/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const BuilderResumeIdRouteRoute = BuilderResumeIdRouteRouteImport.update({
  id: "/builder/$resumeId",
  path: "/builder/$resumeId",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardResumesIndexRoute = DashboardResumesIndexRouteImport.update({
  id: "/resumes/",
  path: "/resumes/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardCoverLettersIndexRoute =
  DashboardCoverLettersIndexRouteImport.update({
    id: "/cover-letters/",
    path: "/cover-letters/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const CoverLetterIdIndexRoute = CoverLetterIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => CoverLetterIdRouteRoute,
} as any);
const BuilderResumeIdIndexRoute = BuilderResumeIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => BuilderResumeIdRouteRoute,
} as any);
const UploadsUserIdSplatRoute = UploadsUserIdSplatRouteImport.update({
  id: "/uploads/$userId/$",
  path: "/uploads/$userId/$",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardSettingsProfileRoute =
  DashboardSettingsProfileRouteImport.update({
    id: "/settings/profile",
    path: "/settings/profile",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardSettingsPreferencesRoute =
  DashboardSettingsPreferencesRouteImport.update({
    id: "/settings/preferences",
    path: "/settings/preferences",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardSettingsIntegrationsRoute =
  DashboardSettingsIntegrationsRouteImport.update({
    id: "/settings/integrations",
    path: "/settings/integrations",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardSettingsDangerZoneRoute =
  DashboardSettingsDangerZoneRouteImport.update({
    id: "/settings/danger-zone",
    path: "/settings/danger-zone",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardSettingsApiKeysRoute =
  DashboardSettingsApiKeysRouteImport.update({
    id: "/settings/api-keys",
    path: "/settings/api-keys",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardSettingsAiRoute = DashboardSettingsAiRouteImport.update({
  id: "/settings/ai",
  path: "/settings/ai",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardCoverLettersListRoute =
  DashboardCoverLettersListRouteImport.update({
    id: "/cover-letters/list",
    path: "/cover-letters/list",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: "/api/rpc/$",
  path: "/api/rpc/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiOpenapiSplatRoute = ApiOpenapiSplatRouteImport.update({
  id: "/api/openapi/$",
  path: "/api/openapi/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const BuilderCoverLetterIdRouteRoute =
  BuilderCoverLetterIdRouteRouteImport.update({
    id: "/builder/cover-letter/$id",
    path: "/builder/cover-letter/$id",
    getParentRoute: () => rootRouteImport,
  } as any);
const DashboardSettingsAuthenticationIndexRoute =
  DashboardSettingsAuthenticationIndexRouteImport.update({
    id: "/settings/authentication/",
    path: "/settings/authentication/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const BuilderCoverLetterIdIndexRoute =
  BuilderCoverLetterIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => BuilderCoverLetterIdRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof HomeIndexRoute;
  "/auth": typeof AuthRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/schema.json": typeof SchemaDotjsonRoute;
  "/builder/$resumeId": typeof BuilderResumeIdRouteRouteWithChildren;
  "/cover-letter/$id": typeof CoverLetterIdRouteRouteWithChildren;
  "/$username/$slug": typeof UsernameSlugRoute;
  "/api/health": typeof ApiHealthRoute;
  "/api/simple-auth": typeof ApiSimpleAuthRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/register": typeof AuthRegisterRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/auth/resume-password": typeof AuthResumePasswordRoute;
  "/auth/verify-2fa": typeof AuthVerify2faRoute;
  "/auth/verify-2fa-backup": typeof AuthVerify2faBackupRoute;
  "/dashboard/history": typeof DashboardHistoryRoute;
  "/printer/$resumeId": typeof PrinterResumeIdRoute;
  "/auth/": typeof AuthIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/builder/cover-letter/$id": typeof BuilderCoverLetterIdRouteRouteWithChildren;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/openapi/$": typeof ApiOpenapiSplatRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/dashboard/cover-letters/list": typeof DashboardCoverLettersListRoute;
  "/dashboard/settings/ai": typeof DashboardSettingsAiRoute;
  "/dashboard/settings/api-keys": typeof DashboardSettingsApiKeysRoute;
  "/dashboard/settings/danger-zone": typeof DashboardSettingsDangerZoneRoute;
  "/dashboard/settings/integrations": typeof DashboardSettingsIntegrationsRoute;
  "/dashboard/settings/preferences": typeof DashboardSettingsPreferencesRoute;
  "/dashboard/settings/profile": typeof DashboardSettingsProfileRoute;
  "/uploads/$userId/$": typeof UploadsUserIdSplatRoute;
  "/builder/$resumeId/": typeof BuilderResumeIdIndexRoute;
  "/cover-letter/$id/": typeof CoverLetterIdIndexRoute;
  "/dashboard/cover-letters/": typeof DashboardCoverLettersIndexRoute;
  "/dashboard/resumes/": typeof DashboardResumesIndexRoute;
  "/builder/cover-letter/$id/": typeof BuilderCoverLetterIdIndexRoute;
  "/dashboard/settings/authentication/": typeof DashboardSettingsAuthenticationIndexRoute;
}
export interface FileRoutesByTo {
  "/schema.json": typeof SchemaDotjsonRoute;
  "/$username/$slug": typeof UsernameSlugRoute;
  "/api/health": typeof ApiHealthRoute;
  "/api/simple-auth": typeof ApiSimpleAuthRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/register": typeof AuthRegisterRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/auth/resume-password": typeof AuthResumePasswordRoute;
  "/auth/verify-2fa": typeof AuthVerify2faRoute;
  "/auth/verify-2fa-backup": typeof AuthVerify2faBackupRoute;
  "/dashboard/history": typeof DashboardHistoryRoute;
  "/printer/$resumeId": typeof PrinterResumeIdRoute;
  "/": typeof HomeIndexRoute;
  "/auth": typeof AuthIndexRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/openapi/$": typeof ApiOpenapiSplatRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/dashboard/cover-letters/list": typeof DashboardCoverLettersListRoute;
  "/dashboard/settings/ai": typeof DashboardSettingsAiRoute;
  "/dashboard/settings/api-keys": typeof DashboardSettingsApiKeysRoute;
  "/dashboard/settings/danger-zone": typeof DashboardSettingsDangerZoneRoute;
  "/dashboard/settings/integrations": typeof DashboardSettingsIntegrationsRoute;
  "/dashboard/settings/preferences": typeof DashboardSettingsPreferencesRoute;
  "/dashboard/settings/profile": typeof DashboardSettingsProfileRoute;
  "/uploads/$userId/$": typeof UploadsUserIdSplatRoute;
  "/builder/$resumeId": typeof BuilderResumeIdIndexRoute;
  "/cover-letter/$id": typeof CoverLetterIdIndexRoute;
  "/dashboard/cover-letters": typeof DashboardCoverLettersIndexRoute;
  "/dashboard/resumes": typeof DashboardResumesIndexRoute;
  "/builder/cover-letter/$id": typeof BuilderCoverLetterIdIndexRoute;
  "/dashboard/settings/authentication": typeof DashboardSettingsAuthenticationIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_home": typeof HomeRouteRouteWithChildren;
  "/auth": typeof AuthRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/schema.json": typeof SchemaDotjsonRoute;
  "/builder/$resumeId": typeof BuilderResumeIdRouteRouteWithChildren;
  "/cover-letter/$id": typeof CoverLetterIdRouteRouteWithChildren;
  "/$username/$slug": typeof UsernameSlugRoute;
  "/api/health": typeof ApiHealthRoute;
  "/api/simple-auth": typeof ApiSimpleAuthRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/register": typeof AuthRegisterRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/auth/resume-password": typeof AuthResumePasswordRoute;
  "/auth/verify-2fa": typeof AuthVerify2faRoute;
  "/auth/verify-2fa-backup": typeof AuthVerify2faBackupRoute;
  "/dashboard/history": typeof DashboardHistoryRoute;
  "/printer/$resumeId": typeof PrinterResumeIdRoute;
  "/_home/": typeof HomeIndexRoute;
  "/auth/": typeof AuthIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/builder/cover-letter/$id": typeof BuilderCoverLetterIdRouteRouteWithChildren;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/openapi/$": typeof ApiOpenapiSplatRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/dashboard/cover-letters/list": typeof DashboardCoverLettersListRoute;
  "/dashboard/settings/ai": typeof DashboardSettingsAiRoute;
  "/dashboard/settings/api-keys": typeof DashboardSettingsApiKeysRoute;
  "/dashboard/settings/danger-zone": typeof DashboardSettingsDangerZoneRoute;
  "/dashboard/settings/integrations": typeof DashboardSettingsIntegrationsRoute;
  "/dashboard/settings/preferences": typeof DashboardSettingsPreferencesRoute;
  "/dashboard/settings/profile": typeof DashboardSettingsProfileRoute;
  "/uploads/$userId/$": typeof UploadsUserIdSplatRoute;
  "/builder/$resumeId/": typeof BuilderResumeIdIndexRoute;
  "/cover-letter/$id/": typeof CoverLetterIdIndexRoute;
  "/dashboard/cover-letters/": typeof DashboardCoverLettersIndexRoute;
  "/dashboard/resumes/": typeof DashboardResumesIndexRoute;
  "/builder/cover-letter/$id/": typeof BuilderCoverLetterIdIndexRoute;
  "/dashboard/settings/authentication/": typeof DashboardSettingsAuthenticationIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/auth"
    | "/dashboard"
    | "/schema.json"
    | "/builder/$resumeId"
    | "/cover-letter/$id"
    | "/$username/$slug"
    | "/api/health"
    | "/api/simple-auth"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/register"
    | "/auth/reset-password"
    | "/auth/resume-password"
    | "/auth/verify-2fa"
    | "/auth/verify-2fa-backup"
    | "/dashboard/history"
    | "/printer/$resumeId"
    | "/auth/"
    | "/dashboard/"
    | "/builder/cover-letter/$id"
    | "/api/auth/$"
    | "/api/openapi/$"
    | "/api/rpc/$"
    | "/dashboard/cover-letters/list"
    | "/dashboard/settings/ai"
    | "/dashboard/settings/api-keys"
    | "/dashboard/settings/danger-zone"
    | "/dashboard/settings/integrations"
    | "/dashboard/settings/preferences"
    | "/dashboard/settings/profile"
    | "/uploads/$userId/$"
    | "/builder/$resumeId/"
    | "/cover-letter/$id/"
    | "/dashboard/cover-letters/"
    | "/dashboard/resumes/"
    | "/builder/cover-letter/$id/"
    | "/dashboard/settings/authentication/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/schema.json"
    | "/$username/$slug"
    | "/api/health"
    | "/api/simple-auth"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/register"
    | "/auth/reset-password"
    | "/auth/resume-password"
    | "/auth/verify-2fa"
    | "/auth/verify-2fa-backup"
    | "/dashboard/history"
    | "/printer/$resumeId"
    | "/"
    | "/auth"
    | "/dashboard"
    | "/api/auth/$"
    | "/api/openapi/$"
    | "/api/rpc/$"
    | "/dashboard/cover-letters/list"
    | "/dashboard/settings/ai"
    | "/dashboard/settings/api-keys"
    | "/dashboard/settings/danger-zone"
    | "/dashboard/settings/integrations"
    | "/dashboard/settings/preferences"
    | "/dashboard/settings/profile"
    | "/uploads/$userId/$"
    | "/builder/$resumeId"
    | "/cover-letter/$id"
    | "/dashboard/cover-letters"
    | "/dashboard/resumes"
    | "/builder/cover-letter/$id"
    | "/dashboard/settings/authentication";
  id:
    | "__root__"
    | "/_home"
    | "/auth"
    | "/dashboard"
    | "/schema.json"
    | "/builder/$resumeId"
    | "/cover-letter/$id"
    | "/$username/$slug"
    | "/api/health"
    | "/api/simple-auth"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/register"
    | "/auth/reset-password"
    | "/auth/resume-password"
    | "/auth/verify-2fa"
    | "/auth/verify-2fa-backup"
    | "/dashboard/history"
    | "/printer/$resumeId"
    | "/_home/"
    | "/auth/"
    | "/dashboard/"
    | "/builder/cover-letter/$id"
    | "/api/auth/$"
    | "/api/openapi/$"
    | "/api/rpc/$"
    | "/dashboard/cover-letters/list"
    | "/dashboard/settings/ai"
    | "/dashboard/settings/api-keys"
    | "/dashboard/settings/danger-zone"
    | "/dashboard/settings/integrations"
    | "/dashboard/settings/preferences"
    | "/dashboard/settings/profile"
    | "/uploads/$userId/$"
    | "/builder/$resumeId/"
    | "/cover-letter/$id/"
    | "/dashboard/cover-letters/"
    | "/dashboard/resumes/"
    | "/builder/cover-letter/$id/"
    | "/dashboard/settings/authentication/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  HomeRouteRoute: typeof HomeRouteRouteWithChildren;
  AuthRouteRoute: typeof AuthRouteRouteWithChildren;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
  SchemaDotjsonRoute: typeof SchemaDotjsonRoute;
  BuilderResumeIdRouteRoute: typeof BuilderResumeIdRouteRouteWithChildren;
  CoverLetterIdRouteRoute: typeof CoverLetterIdRouteRouteWithChildren;
  UsernameSlugRoute: typeof UsernameSlugRoute;
  ApiHealthRoute: typeof ApiHealthRoute;
  ApiSimpleAuthRoute: typeof ApiSimpleAuthRoute;
  PrinterResumeIdRoute: typeof PrinterResumeIdRoute;
  BuilderCoverLetterIdRouteRoute: typeof BuilderCoverLetterIdRouteRouteWithChildren;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiOpenapiSplatRoute: typeof ApiOpenapiSplatRoute;
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute;
  UploadsUserIdSplatRoute: typeof UploadsUserIdSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/schema.json": {
      id: "/schema.json";
      path: "/schema.json";
      fullPath: "/schema.json";
      preLoaderRoute: typeof SchemaDotjsonRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth": {
      id: "/auth";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof AuthRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_home": {
      id: "/_home";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof HomeRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/auth/": {
      id: "/auth/";
      path: "/";
      fullPath: "/auth/";
      preLoaderRoute: typeof AuthIndexRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_home/": {
      id: "/_home/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof HomeIndexRouteImport;
      parentRoute: typeof HomeRouteRoute;
    };
    "/printer/$resumeId": {
      id: "/printer/$resumeId";
      path: "/printer/$resumeId";
      fullPath: "/printer/$resumeId";
      preLoaderRoute: typeof PrinterResumeIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/history": {
      id: "/dashboard/history";
      path: "/history";
      fullPath: "/dashboard/history";
      preLoaderRoute: typeof DashboardHistoryRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/auth/verify-2fa-backup": {
      id: "/auth/verify-2fa-backup";
      path: "/verify-2fa-backup";
      fullPath: "/auth/verify-2fa-backup";
      preLoaderRoute: typeof AuthVerify2faBackupRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/verify-2fa": {
      id: "/auth/verify-2fa";
      path: "/verify-2fa";
      fullPath: "/auth/verify-2fa";
      preLoaderRoute: typeof AuthVerify2faRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/resume-password": {
      id: "/auth/resume-password";
      path: "/resume-password";
      fullPath: "/auth/resume-password";
      preLoaderRoute: typeof AuthResumePasswordRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/reset-password": {
      id: "/auth/reset-password";
      path: "/reset-password";
      fullPath: "/auth/reset-password";
      preLoaderRoute: typeof AuthResetPasswordRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/register": {
      id: "/auth/register";
      path: "/register";
      fullPath: "/auth/register";
      preLoaderRoute: typeof AuthRegisterRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/login": {
      id: "/auth/login";
      path: "/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/forgot-password": {
      id: "/auth/forgot-password";
      path: "/forgot-password";
      fullPath: "/auth/forgot-password";
      preLoaderRoute: typeof AuthForgotPasswordRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/api/simple-auth": {
      id: "/api/simple-auth";
      path: "/api/simple-auth";
      fullPath: "/api/simple-auth";
      preLoaderRoute: typeof ApiSimpleAuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/health": {
      id: "/api/health";
      path: "/api/health";
      fullPath: "/api/health";
      preLoaderRoute: typeof ApiHealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$username/$slug": {
      id: "/$username/$slug";
      path: "/$username/$slug";
      fullPath: "/$username/$slug";
      preLoaderRoute: typeof UsernameSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/cover-letter/$id": {
      id: "/cover-letter/$id";
      path: "/cover-letter/$id";
      fullPath: "/cover-letter/$id";
      preLoaderRoute: typeof CoverLetterIdRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/builder/$resumeId": {
      id: "/builder/$resumeId";
      path: "/builder/$resumeId";
      fullPath: "/builder/$resumeId";
      preLoaderRoute: typeof BuilderResumeIdRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/resumes/": {
      id: "/dashboard/resumes/";
      path: "/resumes";
      fullPath: "/dashboard/resumes/";
      preLoaderRoute: typeof DashboardResumesIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/cover-letters/": {
      id: "/dashboard/cover-letters/";
      path: "/cover-letters";
      fullPath: "/dashboard/cover-letters/";
      preLoaderRoute: typeof DashboardCoverLettersIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/cover-letter/$id/": {
      id: "/cover-letter/$id/";
      path: "/";
      fullPath: "/cover-letter/$id/";
      preLoaderRoute: typeof CoverLetterIdIndexRouteImport;
      parentRoute: typeof CoverLetterIdRouteRoute;
    };
    "/builder/$resumeId/": {
      id: "/builder/$resumeId/";
      path: "/";
      fullPath: "/builder/$resumeId/";
      preLoaderRoute: typeof BuilderResumeIdIndexRouteImport;
      parentRoute: typeof BuilderResumeIdRouteRoute;
    };
    "/uploads/$userId/$": {
      id: "/uploads/$userId/$";
      path: "/uploads/$userId/$";
      fullPath: "/uploads/$userId/$";
      preLoaderRoute: typeof UploadsUserIdSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/settings/profile": {
      id: "/dashboard/settings/profile";
      path: "/settings/profile";
      fullPath: "/dashboard/settings/profile";
      preLoaderRoute: typeof DashboardSettingsProfileRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings/preferences": {
      id: "/dashboard/settings/preferences";
      path: "/settings/preferences";
      fullPath: "/dashboard/settings/preferences";
      preLoaderRoute: typeof DashboardSettingsPreferencesRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings/integrations": {
      id: "/dashboard/settings/integrations";
      path: "/settings/integrations";
      fullPath: "/dashboard/settings/integrations";
      preLoaderRoute: typeof DashboardSettingsIntegrationsRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings/danger-zone": {
      id: "/dashboard/settings/danger-zone";
      path: "/settings/danger-zone";
      fullPath: "/dashboard/settings/danger-zone";
      preLoaderRoute: typeof DashboardSettingsDangerZoneRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings/api-keys": {
      id: "/dashboard/settings/api-keys";
      path: "/settings/api-keys";
      fullPath: "/dashboard/settings/api-keys";
      preLoaderRoute: typeof DashboardSettingsApiKeysRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings/ai": {
      id: "/dashboard/settings/ai";
      path: "/settings/ai";
      fullPath: "/dashboard/settings/ai";
      preLoaderRoute: typeof DashboardSettingsAiRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/cover-letters/list": {
      id: "/dashboard/cover-letters/list";
      path: "/cover-letters/list";
      fullPath: "/dashboard/cover-letters/list";
      preLoaderRoute: typeof DashboardCoverLettersListRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/api/rpc/$": {
      id: "/api/rpc/$";
      path: "/api/rpc/$";
      fullPath: "/api/rpc/$";
      preLoaderRoute: typeof ApiRpcSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/openapi/$": {
      id: "/api/openapi/$";
      path: "/api/openapi/$";
      fullPath: "/api/openapi/$";
      preLoaderRoute: typeof ApiOpenapiSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/builder/cover-letter/$id": {
      id: "/builder/cover-letter/$id";
      path: "/builder/cover-letter/$id";
      fullPath: "/builder/cover-letter/$id";
      preLoaderRoute: typeof BuilderCoverLetterIdRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/settings/authentication/": {
      id: "/dashboard/settings/authentication/";
      path: "/settings/authentication";
      fullPath: "/dashboard/settings/authentication/";
      preLoaderRoute: typeof DashboardSettingsAuthenticationIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/builder/cover-letter/$id/": {
      id: "/builder/cover-letter/$id/";
      path: "/";
      fullPath: "/builder/cover-letter/$id/";
      preLoaderRoute: typeof BuilderCoverLetterIdIndexRouteImport;
      parentRoute: typeof BuilderCoverLetterIdRouteRoute;
    };
  }
}

interface HomeRouteRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute;
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
};

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
);

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthRegisterRoute: typeof AuthRegisterRoute;
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute;
  AuthResumePasswordRoute: typeof AuthResumePasswordRoute;
  AuthVerify2faRoute: typeof AuthVerify2faRoute;
  AuthVerify2faBackupRoute: typeof AuthVerify2faBackupRoute;
  AuthIndexRoute: typeof AuthIndexRoute;
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthResumePasswordRoute: AuthResumePasswordRoute,
  AuthVerify2faRoute: AuthVerify2faRoute,
  AuthVerify2faBackupRoute: AuthVerify2faBackupRoute,
  AuthIndexRoute: AuthIndexRoute,
};

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
);

interface DashboardRouteRouteChildren {
  DashboardHistoryRoute: typeof DashboardHistoryRoute;
  DashboardIndexRoute: typeof DashboardIndexRoute;
  DashboardCoverLettersListRoute: typeof DashboardCoverLettersListRoute;
  DashboardSettingsAiRoute: typeof DashboardSettingsAiRoute;
  DashboardSettingsApiKeysRoute: typeof DashboardSettingsApiKeysRoute;
  DashboardSettingsDangerZoneRoute: typeof DashboardSettingsDangerZoneRoute;
  DashboardSettingsIntegrationsRoute: typeof DashboardSettingsIntegrationsRoute;
  DashboardSettingsPreferencesRoute: typeof DashboardSettingsPreferencesRoute;
  DashboardSettingsProfileRoute: typeof DashboardSettingsProfileRoute;
  DashboardCoverLettersIndexRoute: typeof DashboardCoverLettersIndexRoute;
  DashboardResumesIndexRoute: typeof DashboardResumesIndexRoute;
  DashboardSettingsAuthenticationIndexRoute: typeof DashboardSettingsAuthenticationIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCoverLettersListRoute: DashboardCoverLettersListRoute,
  DashboardSettingsAiRoute: DashboardSettingsAiRoute,
  DashboardSettingsApiKeysRoute: DashboardSettingsApiKeysRoute,
  DashboardSettingsDangerZoneRoute: DashboardSettingsDangerZoneRoute,
  DashboardSettingsIntegrationsRoute: DashboardSettingsIntegrationsRoute,
  DashboardSettingsPreferencesRoute: DashboardSettingsPreferencesRoute,
  DashboardSettingsProfileRoute: DashboardSettingsProfileRoute,
  DashboardCoverLettersIndexRoute: DashboardCoverLettersIndexRoute,
  DashboardResumesIndexRoute: DashboardResumesIndexRoute,
  DashboardSettingsAuthenticationIndexRoute:
    DashboardSettingsAuthenticationIndexRoute,
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
);

interface BuilderResumeIdRouteRouteChildren {
  BuilderResumeIdIndexRoute: typeof BuilderResumeIdIndexRoute;
}

const BuilderResumeIdRouteRouteChildren: BuilderResumeIdRouteRouteChildren = {
  BuilderResumeIdIndexRoute: BuilderResumeIdIndexRoute,
};

const BuilderResumeIdRouteRouteWithChildren =
  BuilderResumeIdRouteRoute._addFileChildren(BuilderResumeIdRouteRouteChildren);

interface CoverLetterIdRouteRouteChildren {
  CoverLetterIdIndexRoute: typeof CoverLetterIdIndexRoute;
}

const CoverLetterIdRouteRouteChildren: CoverLetterIdRouteRouteChildren = {
  CoverLetterIdIndexRoute: CoverLetterIdIndexRoute,
};

const CoverLetterIdRouteRouteWithChildren =
  CoverLetterIdRouteRoute._addFileChildren(CoverLetterIdRouteRouteChildren);

interface BuilderCoverLetterIdRouteRouteChildren {
  BuilderCoverLetterIdIndexRoute: typeof BuilderCoverLetterIdIndexRoute;
}

const BuilderCoverLetterIdRouteRouteChildren: BuilderCoverLetterIdRouteRouteChildren =
  {
    BuilderCoverLetterIdIndexRoute: BuilderCoverLetterIdIndexRoute,
  };

const BuilderCoverLetterIdRouteRouteWithChildren =
  BuilderCoverLetterIdRouteRoute._addFileChildren(
    BuilderCoverLetterIdRouteRouteChildren,
  );

const rootRouteChildren: RootRouteChildren = {
  HomeRouteRoute: HomeRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  SchemaDotjsonRoute: SchemaDotjsonRoute,
  BuilderResumeIdRouteRoute: BuilderResumeIdRouteRouteWithChildren,
  CoverLetterIdRouteRoute: CoverLetterIdRouteRouteWithChildren,
  UsernameSlugRoute: UsernameSlugRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSimpleAuthRoute: ApiSimpleAuthRoute,
  PrinterResumeIdRoute: PrinterResumeIdRoute,
  BuilderCoverLetterIdRouteRoute: BuilderCoverLetterIdRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOpenapiSplatRoute: ApiOpenapiSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  UploadsUserIdSplatRoute: UploadsUserIdSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
